### ISSUE TITLE
peer to peer code review

### ISSUE THREAD

**Issue by EmiLoKiJu** [mpa-mxiang/to-do-list#6]
- Do not allow to add empty elements to the list
- There is a bug where deleting elements on the list, makes no difference in the list itself and only gets updated in the local storage.
- When editing elements, they only get edited on the list, but not in the local storage.
- Nice code :)

**Comment by mpa-mxiang** [comment]
Thank you! @EmiLoKiJu  I fixed the first and the third issues, but I am confused about the second issue you mentioned, can you explain more clearer?

**Comment by EmiLoKiJu** [comment]
Hi there @mpa-mxiang ~ 
In the GIF, you can press the trash icon, and delete elements from the local storage, but the list itself, in the DOM, is not edited.
(I just updated the new GIF because of the resolution)
![2023-05-11-13-13-55_Trim](https://github.com/mpa-mxiang/to-do-list/assets/84760694/61fc46b5-9c08-458c-bd02-5241886e16c5)
I hope this helps~

**Comment by mpa-mxiang** [comment]
Got it, I think it is because I stored in the wrong local storage, I will change it, thank you!
